### PR TITLE
[RFR] Feature/sf5 support

### LINKED ISSUE #226: Add support for Symfony 5

### PR DESCRIPTION
**Pull request by nm2107**
Fixes #226 .

### CODE REVIEW

**Comment by garak** [comment]
@nm2107 to make tests passing, you should change `root_dir` with `project_dir` in `Tests/Functional/Resources/config/config.yml`

**Comment by nm2107** [comment]
:thinking: I removed `php 7.4` from test matrix as it is not supported by travis yet : https://travis-ci.org/KnpLabs/KnpGaufretteBundle/jobs/619482828

**Comment by garak** [comment]
You should use `7.4snapshot`

**Comment by Vincz** [comment]
Hey guys :) Could this be merge soon? There is not so much to review.
Thanks for the great bundle!

ping @NiR- 
ping @alexpozzi

**Pull request merged**
