### PR TITLE
Drop support for old PHP versions 5.3, 5.4, 5.5

### PR DESCRIPTION
**Pull request by rjd22**

### CODE REVIEW

**Comment by rjd22** [comment]
@NiR- Lets hope this fixed the build :)

**Comment by NiR-** [comment]
Thank you @rjd22 :) Last step before release: write the changelog for v0.5. Could you write it, if you don't mind? After that, we should be ready to release :)

**Comment by rjd22** [comment]
@NiR- I can write the change log but don't know of all the changes made to the bundle. What are the major changes made to the bundle? I will make the PR for it changing the changelog and version.

Also I see that the readme advises to copy and paste the dependency in the composer.json. nowadays the recommended way would be doing `composer require knplabs/knp-gaufrette-bundle`. Do you mind if I change that also?

**Comment by NiR-** [comment]
No worry, I have finally some free time this noon to do it, and I'll update the readme ;)

**Comment by rjd22** [comment]
@NiR- thank you for releasing :)

**Pull request merged**
