### PR TITLE
PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by kralmichal**

### CODE REVIEW

**Comment by Nek-** [comment]
Adding in the comment the return type `@return \Traversable` would be great.

**Comment by rimas-kudelis** [comment]
I believe that properly typehinting the value that is being returned would be a better fix. With PHP7.4 being the last version of PHP7 that still has just over 8 months of security support left, I see no reason at all to maintain compatibility with the older versions anymore.

**Comment by kralmichal** [comment]
@nm2107 Would it be possible to merge this and make a release?

**Review by Nek- — APPROVED** [review]

**Comment by kralmichal** [comment]
> Let me ask the maintainers (I'm not in the organization anymore). Thank you for this PR.

Thank you

**Comment by rimas-kudelis** [comment]
Guys, please consider #259 as well. I'm certain that that approach is better than this.

**Comment by kralmichal** [comment]
> Guys, please consider #259 as well. I'm certain that that approach is better than this.

Sure it is. I would be happy either way, just to get rid off the deprecation notices. I guess there could be a BC break with #256 but think it would be real edge-case.

**Comment by Nek-** [comment]
@rimas-kudelis thank you for pointing out the other PR but it breaks the compatibility. This should be merged either in a major version or just _later_ . Actually it should be great to consider but needs to be study a little more.

**Comment by rimas-kudelis** [comment]
Yes, I guess it would mandate a major release, and a major release could benefit from more typehinting/cleanup than just these two methods.

I guess it would be dumb of me to attempt to block a minor release just because a better fix exists. I hereby concede.

**Comment by jukuan** [comment]
Guys, I can add more typehinting in the next PR if it's needed.

I started the small Pull Request #259 because I faced with the issue, that's why i forked your repo. And I can see that's i am not alone :)

**Comment by Nek-** [comment]
Thank you @kralmichal :) .

**Pull request merged**
