### PR TITLE
Add support for Google Cloud Storage

### PR DESCRIPTION
**Pull request by patkar**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | n/a
| Fixed tickets | n/a 
| License       | MIT

Depends on merging KnpLabs/Gaufrette#313 first.

### CODE REVIEW

**Comment by patkar** [comment]
Any chance to get this merged?

**Comment by mappedinn** [comment]
Is there any reason for not accepting the PR og @patkar ??? @docteurklein

**Comment by docteurklein** [comment]
@mappedinn the lack of time. Sorry for that. But I'm not the moist qualified to decide a feature merge since i'm not a big user of gaufrette anyway.

**Comment by patkar** [comment]
I hope it works without problems. @docteurklein @mappedinn Feel free to ping me in issues on gaufrette for the GCS implementation.

**Comment by mappedinn** [comment]
thank you so much @docteurklein @patkar 

@patkar I will be back to you if there is any problem.

**Pull request merged**
